name: Share data between jobs

on: [push]

jobs:
  get_current_duplicacy:
    name: Get current version of duplicacy
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          echo ${$(curl -Ls https://api.github.com/repos/gilbertchen/duplicacy/tags | awk -F'"' '/name.*v[0-9]/ {print $4; exit}'):1} > current_duplicacy_version.txt
      - name: Upload math result for get_current_duplicacy
        uses: actions/upload-artifact@v2
        with:
          name: current_duplicacy_version
          path: current_duplicacy_version.txt

  print_current_duplicacy:
    name: Print current version of duplicacy
    needs: get_current_duplicacy
    runs-on: ubuntu-latest
    steps:
      - name: Download math result for get_current_duplicacy
        uses: actions/download-artifact@v2
        with:
          name: current_duplicacy_version
      - shell: bash
        run: |
          value=`cat math-homework.txt`
          echo "Current duplicacy version = "$value
