name: Share data between jobs

on: [push]

jobs:
  print_current_duplicacy:
    name: Print current version of duplicacy
    runs-on: ubuntu-latest
    steps:
      - name: Download math result for get_current_duplicacy
        uses: actions/download-artifact@v2
        with:
          name: current_duplicacy_version
      - shell: bash
        run: |
          value=`cat current_duplicacy_version.txt`
          echo "Current duplicacy version = "$value
