name: Share data between jobs

on: [workflow_dispatch]

env:
  DUPLICACY_VERSION: ""
  S6_OVERLAY_VERSION: ""

jobs:
  get_current_duplicacy:
    name: Get current version of duplicacy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get branch name
        id: git
        run: |
          NAME=$(echo ${GITHUB_REF} | sed -e "s/.*\///g")
          TAG=false
          if [[ ${GITHUB_REF} == *"/tags/"* ]]; then
            TAG=true
          fi
          echo name=${NAME}  tag=${TAG}  ref=${GITHUB_REF}
          echo "::set-output name=name::${NAME}"
          echo "::set-output name=tag::${TAG}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: amd64,arm64,arm,386

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - shell: bash
        run: |
          github_repo_latest_tag()
          {
              local repo=$1
              echo $(curl -Ls https://api.github.com/repos/$repo/tags | awk -F'"' '/name.*v[0-9]/ {print $4; exit}')
          }
          github_repo_latest_version()
          {
              local repo=$1
              local latest_tag=$(github_repo_latest_tag $repo)
              local version="${latest_tag:1}"
              echo $version
          }
          echo "DUPLICACY_VERSION=$(github_repo_latest_version gilbertchen/duplicacy)" >> $GITHUB_ENV
          echo "S6_OVERLAY_VERSION=$(github_repo_latest_version just-containers/s6-overlay)" >> $GITHUB_ENV

      - shell: bash
        run: |
          echo DUPLICACY_VERSION=${{ env.DUPLICACY_VERSION }} | tee settings.conf
          echo S6_OVERLAY_VERSION=${{ env.S6_OVERLAY_VERSION }} | tee -a settings.conf

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'Update settings.conf'
          add: 'settings.conf'