name: CI_CD_Task

on:
  push:

jobs:
  update_config_build_and_deploy:
    name: Build and publish Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Get branch name
        id: branch
        shell: bash
        run: |
          VALUE=$(echo ${GITHUB_REF} | sed -e "s/.*\///g")
          echo "Action branch=$VALUE"

      - name: Get build date
        id: date
        shell: bash
        run: |
          VALUE=`date +%F_%H-%M-%S`
          echo "Build date=$VALUE"

      - name: Login to DockerHub
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.3.0

      - name: Build and push latest and sha
        if: ${{ steps.branch.value == 'main' || steps.branch.value == 'master' }}
        uses: docker/build-push-action@v2.5.0
        with:
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6
          push: true
          tags: |
            ${{ github.repository }}:latest-${{ steps.date.value }}
            ghcr.io/${{ github.repository }}:latest-${{ steps.date.value }}
            ${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:latest

      - name: Build and push branch
        if: ${{ steps.branch.value != 'main' && steps.branch.value != 'master' }}
        uses: docker/build-push-action@v2.5.0
        with:
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6
          push: true
          tags: |
            ${{ github.repository }}:${{ steps.branch.value }}
            ghcr.io/${{ github.repository }}:${{ steps.branch.value }}

      - name: Update repo description
        if: ${{ steps.branch.value == 'main' || steps.branch.value == 'master' }}
        uses: peter-evans/dockerhub-description@v2.4.3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ github.repository }}
          short-description: ${{ github.event.repository.description }}
