name: nightly_build

on:
#  schedule:
#    - cron: 0 2 * * *
  repository_dispatch:
    types: [__FAKE_DISPATCH__]

env:
  CONFIG_FILE: settings.conf
  CONFIG_DUPLICACY_VERSION: ""

jobs:
  nightly_build:
    name: Nightly build of Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: edge

      - name: Read config file
        shell: bash
        run: |
          source ${{ env.CONFIG_FILE }}

          echo "CONFIG_DUPLICACY_VERSION=$DUPLICACY_VERSION" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.3.0

      - name: Login to DockerHub
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build and push edge
        uses: docker/build-push-action@v2.5.0
        with:
          platforms: linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6
          build-args: DUPLICACY_VERSION=${{ env.CONFIG_DUPLICACY_VERSION }}
          push: true
          tags: |
            ${{ github.repository }}:edge
            ghcr.io/${{ github.repository }}:edge
