name: Update_GitHub_package_versions

on:
  push:
  schedule:
    - cron: 0 */3 * * *

env:
  CONFIG_FILE: "github_packages.json"

jobs:
  update_github_releases:
    name: Update github package versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository: ["gilbertchen/duplicacy", "just-containers/s6-overlay"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Get branch name
        id: branch
        shell: bash
        run: |
          raised_from_pr=$(echo ${GITHUB_REF} | grep -q "packageupdaterbot/"; if (( ! $? ));then echo "yes";else echo "no";fi)
          echo "::set-output name=raised_from_pr::$raised_from_pr"

          branch=$(echo ${GITHUB_REF} | sed -e "s/.*\///g")
          echo "::set-output name=branch::$branch"

          echo "Base branch=$branch, raised_from_pr=$raised_from_pr"

      - name: Create package versions file if not exists
        if: ${{ steps.branch.outputs.raised_from_pr == 'no' }}
        shell: bash
        run: |
          if [[ ! -f "${{ env.CONFIG_FILE }}" ]]; then
            echo "${{ env.CONFIG_FILE }} not found, create empty"
            echo "[]" > ${{ env.CONFIG_FILE }}
          fi

      - name: Create node if not exists
        if: ${{ steps.branch.outputs.raised_from_pr == 'no' }}
        shell: bash
        run: |
          NODE=`jq -r '.[] | select(.name == "${{ matrix.repository }}").name'`

          if [[ NODE != ${{ matrix.repository }} ]]; then
            echo "Information about ${{ matrix.repository }} package not found in ${{ env.CONFIG_FILE }}, create empty"
            echo "TEMPORARILY NOT SUPPORTED, update ${{ env.CONFIG_FILE }} manually"
          fi

      - name: Read config version
        if: ${{ steps.branch.outputs.raised_from_pr == 'no' }}
        id: config_version
        shell: bash
        run: |
          version=$(jq -r '.[] | select(.name == "'${{ matrix.repository }}'").version' ${{ env.CONFIG_FILE }})
          echo "::set-output name=version::$version"
          echo "Config version=$version"

      - name: Read repository version
        if: ${{ steps.branch.outputs.raised_from_pr == 'no' }}
        id: repository_version
        shell: bash
        run: |
          latest_tag=$(curl -Ls https://api.github.com/repos/${{ matrix.repository }}/tags | jq -r "first.name")
          version="${latest_tag:1}"
          branch="packageupdaterbot/${{ matrix.repository }}-$version"
          echo "::set-output name=version::$version"
          echo "::set-output name=branch::$branch"
          echo "Repository version=$version, branch=$branch"

      - name: Test PR already exists
        if: ${{ steps.branch.outputs.raised_from_pr == 'no' }}
        id: test_pr
        shell: bash
        run: |
          found=$(git branch -r | grep -q ${{ steps.repository_version.outputs.branch }}; if (( ! $? ));then echo "yes";else echo "no";fi)
          echo "::set-output name=found::$found"
          echo "PR found $found"

      - name: Update ${{ env.CONFIG_FILE }}
        if: ${{ (steps.config_version.outputs.version != steps.repository_version.outputs.version) &&
                (steps.test_pr.outputs.found == 'no') &&
                (steps.branch.outputs.raised_from_pr == 'no') }}
        shell: bash
        run: |
          tempfilename=$(tempfile -d .)
          jq '.[] | select(.name == "'${{ matrix.repository }}'").version = "'${{ steps.repository_version.outputs.version }}'"' ${{ env.CONFIG_FILE }} | jq -s > $tempfilename
          mv $tempfilename ${{ env.CONFIG_FILE }}

      - name: Create Pull Request, Bump ${{ matrix.repository }} \
              from ${{ steps.config_version.outputs.version }} \
              to ${{ steps.repository_version.outputs.version }}
        if: ${{ (steps.config_version.outputs.version != steps.repository_version.outputs.version) &&
                (steps.test_pr.outputs.found == 'no') &&
                (steps.branch.outputs.raised_from_pr == 'no') }}
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          token: ${{ secrets.DUPLICACY_REPO_PAT }}
          branch: ${{ steps.repository_version.outputs.branch }}
          commit-message: Bump ${{ matrix.repository }} from ${{ steps.config_version.outputs.version }} \
                          to ${{ steps.repository_version.outputs.version }}
          delete-branch: true
          title: Bump ${{ matrix.repository }} \
                 from ${{ steps.config_version.outputs.version }} \
                 to ${{ steps.repository_version.outputs.version }}
          body: |
            Bump [${{ matrix.repository }}](https://github.com/${{ matrix.repository }}) from ${{ steps.config_version.outputs.version }} to ${{ steps.repository_version.outputs.version }}.

            - Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)
          labels: |
            dependencies
            github_actions
