name: CI_CD_Task

on:
  push:

env:
  CONFIG_FILE: settings.conf
  OLD_DUPLICACY_VERSION: ""
  OLD_S6_OVERLAY_VERSION: ""
  NEW_DUPLICACY_VERSION: ""
  NEW_S6_OVERLAY_VERSION: ""

jobs:
  if_deps_updated:
    name: Check that dependencies updated
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read config file
        shell: bash
        run: |
          github_repo_latest_tag()
          {
              local repo=$1
              echo $(curl -Ls https://api.github.com/repos/$repo/tags | awk -F'"' '/name.*v[0-9]/ {print $4; exit}')
          }
          github_repo_latest_version()
          {
              local repo=$1
              local latest_tag=$(github_repo_latest_tag $repo)
              local version="${latest_tag:1}"
              echo $version
          }

          source ${{ env.CONFIG_FILE }}

          echo "OLD_DUPLICACY_VERSION=$DUPLICACY_VERSION" >> $GITHUB_ENV
          echo "OLD_S6_OVERLAY_VERSION=$S6_OVERLAY_VERSION" >> $GITHUB_ENV

          echo "NEW_DUPLICACY_VERSION=$(github_repo_latest_version gilbertchen/duplicacy)" >> $GITHUB_ENV
          echo "NEW_S6_OVERLAY_VERSION=$(github_repo_latest_version just-containers/s6-overlay)" >> $GITHUB_ENV

      - name: Fire 'on-deps-change' repository dispatch
        if: ${{ env.OLD_DUPLICACY_VERSION != env.NEW_DUPLICACY_VERSION || env.OLD_S6_OVERLAY_VERSION != env.NEW_S6_OVERLAY_VERSION }}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DUPLICACY_REPO_PAT }}
          event-type: on-deps-change
