name: update_dependencies

on:
  push:
#  schedule:
#    - cron: 0 */3 * * *

env:
  CONFIG_FILE: "github_packages.json"

jobs:
  update_github_releases:
    name: Update github dependency releases
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository: ["gilbertchen/duplicacy", "just-containers/s6-overlay"]
    steps:
      - name: Create package versions file if not exists
        shell: bash
        run: |
          if [[ ! -f "${{ env.CONFIG_FILE }}" ]]; then
            echo "${{ env.CONFIG_FILE }} not found, create empty"
            echo "[]" > ${{ env.CONFIG_FILE }}
          fi

      - name: Create node if not exists
        shell: bash
        run: |
          NODE=`jq -r '.[] | select(.name == "${{ matrix.repository }}").name'`

          if [[ NODE != ${{ matrix.repository }} ]]; then
            echo "Information about ${{ matrix.repository }} package not found in ${{ env.CONFIG_FILE }}, create empty"
          fi

      - name: Print value
        shell: bash
        run: |
          echo "GitHub repository=${{ matrix.repository }}"
          jq --version
