#!/usr/bin/with-contenv bash
# shellcheck shell=bash disable=SC1008

if [[ -f .duplicacy ]]; then
    echo "This folder has already been initialized with duplicacy. Not initializing again"
    exit 0
fi

params=""
config_dir=/config
data_dir=/data
filters_file="${config_dir}"/filters

if [[ ! -z ${DUPLICACY_PASSWORD} ]]; then
    params=-e
fi

if [[ ! -z ${INIT_OPTIONS} ]]; then
    params="${params} $INIT_OPTIONS"
fi

if [[ ! -z ${CHUNK_SIZE} ]]; then
    params="${params} -chunk-size $CHUNK_SIZE"
fi

if [[ ! -z ${MAX_CHUNK_SIZE} ]]; then
    params="${params} -max-chunk-size $MAX_CHUNK_SIZE"
fi

if [[ ! -z ${MIN_CHUNK_SIZE} ]]; then
    params="${params} -min-chunk-size $MIN_CHUNK_SIZE"
fi

params="${params} -pref-dir ${config_dir} -repository $data_dir ${SNAPSHOT_ID} $STORAGE_URL"

nice -n ${PRIORITY_LEVEL} duplicacy ${GLOBAL_OPTIONS} init ${params}
exitcode=$?

if [ "${exitcode}" -ne 0 ]; then
    exit "${exitcode}"
fi

if [[ ! -f ${filter}s_file ]] && [[ ! -z "${FILTER_PATTERNS}" ]]; then
    IFS=';'
    read -ra filters <<< "${filter}_PATTERNS"
    for filter in "${filters[@]}"; do
        echo "${filter}" >> ${filter}s_file
    done
fi

exit 0
